Presentation.Web/Controllers/UploaderController.cs
using Application.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO = Application.DTO;
using Enums = Domain.Infrastructure;
using resources = Infrastructure.Resources;
using Domain.Infrastructure;
using System.IO;
using Infrastructure.Logging;
using Application.DTO.Utils;
using System.Collections;
using System.Runtime.InteropServices;
using Infrastructure.Utils.Extensions;

namespace Presentation.Web.Controllers
{
    /// <summary>
    /// UploaderController
    /// </summary>
    public class UploaderController : GlobalController
    {
        private readonly ICommonAppServices appCommon = new CommonAppServices();
        private readonly IExpedienteAppServices appExpediente = new ExpedienteAppServices();

        private readonly Commons active = new Commons();

        /// <summary>
        /// Index desactivado.
        /// </summary>
        /// <returns></returns>
		public ActionResult Index()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            return Redirect(WebConfigValues.Url_MenuSistemas);
        }



        /// <summary>
        /// Carga documentos temporales al sistema.
        /// </summary>
        /// <param name="file"></param>
        /// <param name="TipoDocumentoID"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult UploadFileTemp(HttpPostedFileBase file, int TipoDocumentoID)
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            var frm = Request.Form;

            string Descripcion = active.GetStringValueForm(frm["DescArchivo"]);

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            int UsuarioActive = sso.GetUsuarioActivoID();
            dbLog.UsuarioID = UsuarioActive;

            if (file != null)
            {
                #region Minimo Tamanio

                if (file.ContentLength < 1)
                {
                    return Json(new { Error = 1, Desc = resources.UploadFiles.messageErrorVacio });
                }

                #endregion


                #region Guardar Archivo Temp Dir

                string fileNameTmp, EndPathTmp;

                string BasePath = WebConfigValues.PathBaseRepository;
                string FolderSave = string.Format("\\Temp\\{0}", DateTime.Now.TimeOfDay.Ticks);
                string TmpDir = string.Format("{0}{1}", BasePath, FolderSave);

                try
                {
                    if (!Directory.Exists(TmpDir)) Directory.CreateDirectory(TmpDir);

                    fileNameTmp = Path.GetFileName(CleanFilename(file.FileName));
                    EndPathTmp = Path.Combine(TmpDir, fileNameTmp);

                    file.SaveAs(EndPathTmp);
                }
                catch (Exception ex)
                {
                    Logger.Execute().Error(ex);
                    dbLog.TipoLog = TipoLog.Error;
                    dbLog.Error = "Nombre Archivo: " + file.FileName + " | " + ex.Message.ToString();
                    dbLog.Save();
                    return Json(new { Error = 1, Desc = resources.UploadFiles.msg_NoSeGuardoElArchivo });
                }

                #endregion


                #region Validaciones MimeType + Tamaño

                IList<DTO.Models.AsocTipoDocumentoAdjunto> FormatosPermitidos = appCommon.GetTipoDocumentoAdjuntoByID(TipoDocumentoID);

                //Mime Type
                List<string> MimeTypePermitidos = new List<string>();
                foreach (var item in FormatosPermitidos)
                {
                    foreach (var str in item.DocumentoAdjunto.TipoFormato.FamiliasMimeType)
                    {
                        MimeTypePermitidos.Add(str.Descripcion.Trim());
                    }
                }

                //Simple Mime
                bool cumpleMEXT = MimeTypePermitidos.Any(i => i.Trim() == file.ContentType);
                if (!cumpleMEXT)
                {
                    System.IO.File.Delete(EndPathTmp);
                    return Json(new { Error = 1, Desc = resources.UploadFiles.msg_FormatoNoSoportado, Mime = file.ContentType });
                }

                //Complex Mime
                string MimeTypeFile = GetMimeFromFile(EndPathTmp);
                bool cumpleMIME = MimeTypePermitidos.Any(i => i.Trim() == MimeTypeFile);
                if (!cumpleMIME)
                {
                    System.IO.File.Delete(EndPathTmp);
                    return Json(new { Error = 1, Desc = resources.UploadFiles.msg_FormatoNoSoportado, Mime = MimeTypeFile });
                }

                //Tamaños
                List<int> tamanios = new List<int>();
                foreach (var item in FormatosPermitidos)
                {
                    tamanios.Add(item.DocumentoAdjunto.MaximoTamanoArchivo.Tamano);
                }

                int maximoTamanio = tamanios.Max() * 1048576;
                if (file.ContentLength > maximoTamanio)
                {
                    return Json(new { Error = 1, Desc = resources.UploadFiles.msg_TamanioMaximo });
                }



                #endregion


                #region Save File ECM or Local Repository

                int FileSharePointID = 0;

                string PathFinalArchivo = string.Empty;
                PathFinalArchivo = Path.Combine(FolderSave, fileNameTmp);

                #endregion

                #region Encrypt File Path

                DTO.Models.VersionEncript enc = appCommon.GetLastVersionEncript();
                TheHash xEncode = new TheHash(enc.Cadena);
                string EncodeEnd = WebConfigValues.IsLocalRepository + TipoUploadChar + PathFinalArchivo + TipoUploadChar + FileSharePointID;
                string SHAFile = xEncode.EncryptData(EncodeEnd);

                #endregion
                try
                {
                    #region Save in Store

                    DTO.Models.DocumentoTmp tmp = new DTO.Models.DocumentoTmp();
                    tmp.DocumentoTmpID = 0;
                    tmp.TipoDocumentoID = TipoDocumentoID;
                    tmp.VersionEncriptID = enc.VersionEncriptID;
                    tmp.Hash = SHAFile;
                    tmp.Fecha = ahora;


                    appCommon.DeleteDocumentosTmp(ahora);

                    tmp.DocumentoTmpID = appCommon.SaveDocumentoTmp(tmp);


                    #region CustomParams
                    var _request = Request;
                    List<DTO.ItemForm> Parametros = new List<DTO.ItemForm>();
                    ArrayList lista = new ArrayList();

                    //keys que no se guardan en el Log
                    String[] Filtro = { "__RequestVerificationToken", "Password", "Clave" };

                    foreach (string item in _request.Form.Keys)
                    {
                        DTO.ItemForm p = new DTO.ItemForm();
                        p.Nombre = item;
                        p.Valor = _request.Form[item];

                        if (!Filtro.Contains(item))
                        {
                            Parametros.Add(p);
                        }
                    }

                    foreach (var item in Parametros)
                    {
                        lista.Add(item.Nombre + "=" + item.Valor);
                    }

                    string customParams = string.Join("#", lista.ToArray());
                    #endregion

                    dbLog.CustomParams = "Params: " + customParams + " | Path: " + PathFinalArchivo;
                    dbLog.Save(true, true);

                    #endregion


                    return Json(new
                    {
                        Error = 0,
                        Desc = "",
                        DocumentoTmpID = tmp.DocumentoTmpID,
                        nombreDoc = fileNameTmp,
                        descDoc = Descripcion,
                        fechaDoc = ahora.ToString("dd-MM-yyyy HH:mm:ss"),
                        cssIcon = System.IO.Path.GetExtension(fileNameTmp).Substring(1),
                        //hash = SHAFile,
                        //encID = enc.VersionEncriptID
                    });
                }
                catch (Exception ex)
                {

                    Logger.Execute().Error(ex);
                    dbLog.TipoLog = TipoLog.Error;
                    dbLog.Error = "Nombre Archivo: " + file.FileName + " | " + ex.Message.ToString();
                    dbLog.Save();
                    return Json(new { Error = 1, Desc = resources.UploadFiles.msg_NoSePudoProcesarDocumento });
                }

            }

            return Json(new { Error = 0 });
        }



        /// <summary>
        /// Carga documentos al sistema.
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
		[HttpPost, ValidateAntiForgeryToken]
        public ActionResult SubirArchivo(HttpPostedFileBase file)
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            int UsuarioActive = sso.GetUsuarioActivoID();
            dbLog.UsuarioID = UsuarioActive;

            var frm = Request.Form;
            int CausaID = active.GetIntValueForm(frm["CausaID"]);
            int ExpedienteID = active.GetIntValueForm(frm["ExpedienteID"]);
            int TipoDocumentoID = active.GetIntValueForm(frm["TipoDocumentoID"]);
            string Descripcion = active.GetStringValueForm(frm["Descripcion"]);

            DTO.Models.Causa causa = new Application.DTO.Models.Causa();

Presentation.Web/Views/Shared/_GetTipoParte.cshtml
@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
    bool IsView = (bool)ViewBag.IsView;
    var TipoParte = (Enums.TipoParte)ViewBag.TipoParte;
    var TipoParteID = (int)TipoParte;
    var Lista = ViewBag.Lista as IList<Application.DTO.Models.Parte>;
    int CausaID = (int)ViewBag.CausaID;

    int count = 1;


    //switch (TipoParte)
    //{
    //    case Enums.TipoParte.Recurrente:
    //        break;
    //    case Enums.TipoParte.Recurrido:
    //        break;
    //    case Enums.TipoParte.Apelante:
    //        break;
    //    case Enums.TipoParte.Apelado:
    //        break;
    //    case Enums.TipoParte.Solicitante:
    //        break;
    //    default:
    //        break;
    //}
}

<script>
    ; (function ($) {
        $(function () {

        });
    })(jQuery);

</script>


<fieldset class="x-fieldset">
    <legend class="celeste bold">@TipoParte.ToString()</legend>

    <div class="row">
        <div class="col text-right" id="btnAdd_@TipoParte.ToString()">
            <button type="button" id="" class="btn btn-default" onclick="GetParte(0, '@TipoParte.ToString()', @CausaID, @TipoParteID)">
                <i class="x-icon x-icon-mas3 icon-in-button"></i> Agregar @TipoParte.ToString()
            </button>
        </div>
    </div>



    <table class="table table-striped table-sm table-bordered table-hover x-table allW" id="" style="margin-top:10px">
        <thead>
            <tr>
                <th class="ac" style="">@resources.GlobalResources.TH_Number</th>
                <th class="ac" style="text-align: left !important">RUT<br />Nombre</th>
                <th class="ac" style="">País</th>
                <th class="ac" style="text-align: left !important">RUT<br />Representante</th>
                <th class="ac" style="">Estudio Jurídico</th>
                <th class="ac" style="text-align: left !important">Abogado<br />Email</th>
                <th class="ac" style="">@resources.GlobalResources.TH_Acciones</th>
            </tr>
        </thead>
        <tbody>
            @if (Lista.Count == 0)
            {
                <tr>
                    <td colspan="7" class="ac">&nbsp;&nbsp;@resources.GlobalResources.SinInformacion</td>
                </tr>
            }
            else
            {
                foreach (var item in Lista)
                {
                    <tr>
                        <td class="ac">@count</td>
                        <td>@item.GetRutFormat(item.Rut)<span class="azul db">@item.Nombre</span></td>
                        <td>@item.GetPais()</td>
                        <td>@item.GetRutFormat(item.RutRepresentante)<span class="azul db">@item.NombreRepresentante</span></td>
                        <td>@item.NombreEstudioJuridico</td>
                        <td>
                            <span class="azul db">@item.NombreAbogado</span>
                            <span class="amarillo db">@item.EmailAbogado</span>
                        </td>
                        <td class="ac">
                            @if (!IsView)
                            {
                                <a class='x-title-l' style=''
                                   onclick="GetParte(@item.ParteID, '@TipoParte.ToString()', @CausaID, @TipoParteID)"
                                   href='javascript:void(0);'
                                   title='@resources.GlobalResources.Editar'><i class='x-icon x-icon-edit'></i></a>
                            }
                        </td>

                    </tr>
                    count++;
                }
            }

            
        </tbody>
    </table>


</fieldset>

Presentation.Web/Views/Shared/_UploadFile.cshtml
@using Enums = Domain.Infrastructure;
@using resources = Infrastructure.Resources;

@{
    var FormatosPermitidos = ViewBag.FormatosPermitidos as IList<Application.DTO.Models.AsocTipoDocumentoAdjunto>;
    var TipoDocumentoEnum = (int)ViewBag.TipoDocumentoEnum;

    var DataForm = ViewBag.DataForm as Application.DTO.DataForm;
}

<script>
    ; (function ($) {
        $(function () {


        });
    })(jQuery);

</script>

<fieldset class="x-fieldset">
    <legend class="celeste bold">Documentos adjuntos</legend>

    <div class="alert alert-info" role="alert">
        Al seleccionar un archivo deberá indicar el contenido del mismo en el campo de texto
    </div>

    <form class="" id="frmFileCausa" enctype="multipart/form-data" action="@Url.Action("SubirArchivo", "Uploader")" method="POST">
        @Html.AntiForgeryToken()

        @Html.Hidden("CausaID", DataForm.CausaID)
        @Html.Hidden("ExpedienteID", DataForm.ExpedienteID)

        <input type="hidden" id="_TipoDocumentoID" name="TipoDocumentoID" value="@TipoDocumentoEnum" />

        <div class="form-group row" id="divDescArchivo">
            <label for="Descripcion" id="" class="col-sm-3 col-form-label">Indique el contenido del archivo</label>
            <div class="col-sm-9">
                <input type="text" id="Descripcion" name="Descripcion" class="form-control notBlock" value="" />
            </div>
        </div>

        <div class="input-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input notBlock" id="file" name="file">
                <label class="custom-file-label" for="file"
                       data-browse="@resources.UploadFiles.FileInput_changeText"
                       aria-describedby="inputGroupFileAddon">@resources.UploadFiles.FileInput_inputText</label>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-info btn-file" onclick='$("#frmFileCausa").submit();' type="button" id="inputGroupFileAddon">
                        <i class="x-icon x-icon-upload2 icon-in-upload"></i> @resources.UploadFiles.lblSubirArchivo
                    </button>
                </div>
            </div>
            <small id="" class="form-text text-muted ac" style="margin-bottom: 10px;">
                @resources.GlobalResources.ExtensionesPermitidas: @Html.Raw(Html.GetExtensionesPermitidas(DataForm.AsocTipoDocumentoAdjunto, IncluyeTamanio: true))
            </small>

        </form>


        <div class="table-responsive">

            <table class="@Html.GetBaseTableCSS()" id="">
                <thead>
                    <tr>
                        <th class="ac" style="">#</th>
                        <th class="ac" style="">Nombre Documento</th>
                        <th class="ac" style="">Descripción</th>
                        <th class="ac" style="">Fecha Carga</th>
                        <th class="ac" style="">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.DocumentoCausa.Count > 0)
                    {
                        count = 1;

                        foreach (var item in Model.DocumentoCausa)
                        {
                            <tr>
                                <td class="ac">@count</td>
                                <td class="">@item.NombreArchivoFisico</td>
                                <td style="max-width:200px" class="fixWord">@item.Descripcion</td>
                                <td class="ac">@Html.DatetimeToString(item.Fecha, "dd-MM-yyyy HH:mm")</td>
                                <td class="ac">

                                    <a style="margin-right:2px" href="javascript:void(0)"
                                       onclick='getDownloadFile(@item.DocumentoCausaID, @Model.CausaID, "@item.Hash.Trim()", @TipoDocumentoEnum)'
                                       class="x-title-l" title="@resources.GlobalResources.BtnDescargar">
                                        <i class="x-icon @Html.GetCSS(item.NombreArchivoFisico)" style="cursor: pointer;"></i>
                                    </a>

                                    @if (PuedeAgregarDocumentos)
                                    {
                                        <a href="javascript:void(0)"
                                           onclick='getDeleteFile(@item.DocumentoCausaID, @TipoDocumentoEnum, @item.VersionEncriptID, "@item.Hash.Trim()", @Model.CausaID)'
                                           class="x-title-l" title="@resources.GlobalResources.BtnEliminar">
                                            <i class="x-icon x-icon-delete notRemove" style="cursor: pointer;"></i>
                                        </a>
                                    }

                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="" style="padding:5px 10px;">No hay información para desplegar</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>

    </fieldset>

Presentation.Web/Views/Shared/_UploadFileTemp.cshtml
@using Enums = Domain.Infrastructure;
@using resources = Infrastructure.Resources;

@{
    var FormatosPermitidos = ViewBag.FormatosPermitidos as IList<Application.DTO.Models.AsocTipoDocumentoAdjunto>;
    var TipoDocumentoEnum = (int)ViewBag.TipoDocumentoEnum;

    int TipoDocumentoTemp = (int)Enums.TipoDocumento.Temporal;
}

<script>
    ; (function ($) {
        $(function () {

            fixFakePath("archivo");

            activateFormUploadTemp("UploadFileFrm",
                function () {

                    if (xJSONResult.Error == 1) {
                        showBlockUIError(xJSONResult.Desc);
                        return false;
                    }

                    AppendItemInTable(xJSONResult, 'tableAdjuntos');

                    return true;
                },
                function () {
                    var _DescArchivo = $.trim($("#DescArchivo").val());
                    if (_DescArchivo == "") {
                        showBlockUIError("Debe indicar el contenido del archivo");
                        return false;
                    }

                    var _file = $("input[name='file']").val();
                    if (_file == "") {
                        showBlockUIError(Labels._messageErrorSelect);
                        return false;
                    }
                })

        });
    })(jQuery);


    function AppendItemInTable(obj, tableName) {

        var tr = $("#tampleteDescarga tbody").html();

        tr = tr.replace("{docid}", obj.DocumentoTmpID);
        tr = tr.replace("{docDownload}", obj.DocumentoTmpID);
        tr = tr.replace("{docDelete}", obj.DocumentoTmpID);
        tr = tr.replace("{nombreDoc}", obj.nombreDoc);
        tr = tr.replace("{nombreDoc2}", obj.nombreDoc);
        tr = tr.replace("{descDoc}", obj.descDoc);
        tr = tr.replace("{fechaDoc}", obj.fechaDoc);
        tr = tr.replace("{cssIcon}", obj.cssIcon);
        tr = tr.replace("{nombreDescarga}", obj.nombreDoc);
        tr = tr.replace("{downloadID}", obj.DocumentoTmpID);

        $("#" + tableName + " tbody").append(tr);
        enumerateItems('enumerate');
        callToolTipsGrid(tableName);

        $('#UploadFileFrm').reset();
        $('#UploadFileFrm .custom-file-label').empty();
    }

    function ParseDocsAdjuntos(form) {

        $("#UploadFileFrm .docTmpID").each(function () {
            var txt = $(this).data("docid");
            var obj = "<input type='hidden' name='DocTmpID' value='" + txt + "' />";
            $("#" + form).append(obj);
        });

        $("#UploadFileFrm .nombreDoc").each(function () {
            var txt = $(this).text();
            var obj = "<input type='hidden' name='DocTmpNombre' value='" + txt + "' />";
            $("#" + form).append(obj);
        });

        $("#UploadFileFrm .descDoc").each(function () {
            var txt = $(this).text();
            var obj = "<input type='hidden' name='DocTmpDesc' value='" + txt + "' />";
            $("#" + form).append(obj);
        });

    }

</script>

<form id="UploadFileFrm" method="post" action="@Url.Action("UploadFileTemp", "Uploader")" style="margin-bottom:0;">
    @Html.AntiForgeryToken()

    @*@Html.Hidden("SolicitudID", Model.SolicitudID)*@

    <input type="hidden" id="_TipoDocumentoID" name="TipoDocumentoID" value="@TipoDocumentoEnum" />
    <fieldset class="x-fieldset" style="" id="fsDocumentosAdjuntos">
        <legend class="celeste bold">Documentos adjuntos</legend>

        <div class="alert alert-info" role="alert">
            Al seleccionar un archivo deberá indicar el contenido del mismo en el campo de texto
        </div>

        <div class="form-group row" id="divDescArchivo">
            <label for="DescArchivo" id="" class="col-sm-4 col-form-label">Indique el contenido del archivo</label>
            <div class="col-sm-8">
                <input type="text" id="DescArchivo" name="DescArchivo" class="form-control notBlock" value="" />
            </div>
        </div>

        <div class="input-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input notBlock" id="archivo" name="file">
                <label class="custom-file-label" for="file"
                       data-browse="@resources.UploadFiles.FileInput_changeText"
                       aria-describedby="inputGroupFileAddon">@resources.UploadFiles.FileInput_inputText</label>
                </div>
                <div class="input-group-append">
                    <button class="btn btn-info btn-file" onclick='$("#UploadFileFrm").submit();' type="button" id="inputGroupFileAddon">
                        <i class="x-icon x-icon-upload2 icon-in-upload"></i> @resources.UploadFiles.lblSubirArchivo
                    </button>
                </div>
            </div>
            <small id="" class="form-text text-muted ac" style="margin-bottom: 10px;">
                @resources.GlobalResources.ExtensionesPermitidas: @Html.Raw(Html.GetExtensionesPermitidas(FormatosPermitidos, IncluyeTamanio: true))
            </small>

            <div class="table-responsive">
                <table style="" class="@Html.GetBaseTableCSS() " id="tableAdjuntos">
                    <thead>
                        <tr>
                            <th class="ac" style="">@resources.GlobalResources.TH_Number</th>
                            <th class="ac" style="">Nombre Documento</th>
                            <th class="ac" style="">Descripción</th>
                            <th class="ac" style="">Fecha Carga</th>
                            <th class="ac" style="">@resources.GlobalResources.TH_Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>

        </fieldset>
    </form>


    <table id="tampleteDescarga" style="display:none">
        <tbody>
            <tr>
                <td class="ac docTmpID" data-docid="{docid}"><span class="enumerate">1</span></td>
                <td class="nombreDoc">{nombreDoc}</td>
                <td class="descDoc">{descDoc}</td>
                <td class="ac">{fechaDoc}</td>
                <td class="ac">

                    <a style="margin-right:2px" href="javascript:void(0)"
                       onclick="getDownloadFile({downloadID}, 0, '{nombreDoc2}', @TipoDocumentoTemp)"
                       class="x-title-t" title="@resources.GlobalResources.BtnDescargar">
                        <i class="x-icon {cssIcon}" style="cursor: pointer;"></i>
                    </a>

                    <a href="javascript:void(0)"
                       onclick='getDeleteFileTemp(@TipoDocumentoTemp, {docDelete}, 0, "", 0, this)'
                       class="x-title-t" title="@resources.GlobalResources.BtnEliminar">
                        <i class="x-icon x-icon-delete" style="cursor: pointer;"></i>
                    </a>
                </td>
            </tr>
        </tbody>
    </table>