Presentation.Web/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Application.Services;
using Infrastructure.Logging;
using Presentation.Web.Context;

using DTO = Application.DTO;
using Enums = Domain.Infrastructure;
using WebConfig = Domain.Infrastructure.WebConfigValues;

namespace Presentation.Web.Controllers
{
    /// <summary>
    /// Controller principal MGF
    /// </summary>
    [SiteContext]
    public class MainController : GlobalController
    {
        private readonly ICommonAppServices appCommon = new CommonAppServices();
        private readonly IMailAppServices appMail = new MailAppServices();
        private readonly Commons active = new Commons();

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                if (WebConfig.IsAccesoPublico)
                {
                    Session.Abandon();
                    Session.Clear();
                    Response.Cookies.Clear();

                    if (!string.IsNullOrWhiteSpace(Request.QueryString["profile"]))
                    {
                        int profile = int.Parse(Request.QueryString["profile"]);

                        if (profile == (int)Enums.TipoAcceso.ClaveUnica)
                        {
                            return RedirectToRoute("VistaPublicaAcceso");
                        }
                    }

                    return RedirectToRoute("LoginAnonymous");

                }
                else
                {
                    SsoActionResult sso = new SsoActionResult();
                    sso.ExecuteResult(ControllerContext);

                    bool acceso = sso.IsTDPI() || sso.IsINAPI() || sso.IsSAG() || sso.IsAdministrador();
                    if (!acceso)
                        return Redirect(WebConfig.LogOffAuthenticationSystem);

                    if (sso.IsAdministrador() && !sso.IsTDPI())
                        return RedirectToRoute("ActionInitialAdmin");

                    return RedirectToRoute("EscritorioCausas");
                }
            }
            catch (Exception ex)
            {
                Logger.Execute().Error(ex);
                if (WebConfig.IsAppDebug)
                {
                    throw;
                }
                else
                {
                    return RedirectToAction("Mensaje");
                }

            }

        }


        /// <summary>
        /// Dashboard Externo
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Dashboard()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            bool IsInvitado = sso.IsInvitado();
            bool IsClaveUnica = sso.IsClaveUnica();
            bool IsRequiereMail = false;
            bool IsINAPI = sso.IsINAPI();
            bool IsSAG = sso.IsSAG();
            bool IsAbogado = sso.IsAbogado();

            bool acceso = (IsInvitado || IsINAPI || IsSAG || IsAbogado);
            if (!acceso) return RedirectToRoute("ActionInitialSystem");

            if (IsClaveUnica)
                IsRequiereMail = (sso.UserActive.UsuarioID > 0 && string.IsNullOrWhiteSpace(sso.UserActive.Mail));

            IList<DTO.Models.TipoCausa> TipoCausaList = appCommon.GetTipoCausa(true);

            ViewBag.IsRequiereMail = IsRequiereMail;
            ViewBag.TipoCausa = active.GetTipoCausaByUserActive(TipoCausaList, sso);

            return View();
        }


        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetMiFirma()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            bool IsTDPI = sso.IsTDPI();

            bool acceso = (IsTDPI || !WebConfig.IsAccesoPublico);
            if (!acceso) return RedirectToRoute("ActionInitialSystem");

            try
            {
                DTO.Models.Usuario model = sso.UserActive;
                model.SignerEncrypted = string.Empty;

                DTO.Models.VersionEncript enc = appCommon.GetVersionEncriptById(1);

                string signer = model.Signer.Trim();

                if (!string.IsNullOrWhiteSpace(signer))
                {
                    try
                    {
                        Infrastructure.Utils.TheHash xEncode = new Infrastructure.Utils.TheHash(enc.Cadena.Trim());

                        model.SignerEncrypted = xEncode.DecryptData(model.Signer.Trim());
                    }
                    catch
                    {
                        model.SignerEncrypted = string.Empty;
                    }
                }

                return PartialView("_MiFirma", model);

            }
            catch (Exception ex)
            {
                Logger.Execute().Error(ex);
                throw;
            }
        }


        /// <summary>
        /// SaveMiFirma
        /// </summary>
        /// <param name="SignerUserActive"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult SaveMiFirma(string SignerUserActive)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            bool IsTDPI = sso.IsTDPI();

            bool acceso = (IsTDPI || !WebConfig.IsAccesoPublico);
            if (!acceso) return Response403();

            int UsuarioActive = sso.GetUsuarioActivoID();

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            dbLog.UsuarioID = UsuarioActive;

            try
            {
                DTO.Models.VersionEncript enc = appCommon.GetVersionEncriptById(1);
                Infrastructure.Utils.TheHash xEncode = new Infrastructure.Utils.TheHash(enc.Cadena);

                string EncodeEnd = active.GetStringValueForm(Request.Form["SignerUserActive"]);
                string strEncode = xEncode.EncryptData(EncodeEnd);

                appCommon.SaveSigner(UsuarioActive, strEncode);

                dbLog.TipoLog = Enums.TipoLog.SaveSigner;
                dbLog.Save();

                return Json(0);
            }
            catch (Exception ex)
            {
                active.SetError(ex, dbLog);
                throw;
            }
        }


        #region Email Usuario externo
        /// <summary>
        /// Cambiar email para ciudadnao Logueado.
        /// </summary>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult MisDatos(string lblEmail)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            int UsuarioActive = sso.GetUsuarioActivoID();

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            dbLog.UsuarioID = UsuarioActive;

            try
            {
                bool IsUsuarioRegistrado = (UsuarioActive > 0);
                DTO.Models.Usuario model = new DTO.Models.Usuario();

                if (WebConfig.IsAccesoPublico && IsUsuarioRegistrado)
                {
                    model = appCommon.GetUsuarios().FirstOrDefault(x => x.UsuarioID == UsuarioActive);
                }

                ViewBag.lblEmail = lblEmail;

                return PartialView("_CambiarEmail", model);

            }
            catch (Exception ex)
            {
                active.SetError(ex, dbLog);
                throw;
            }
        }

        /// <summary>
        /// Actualizar Email
        /// </summary>
        /// <param name="email"></param>
        /// <param name="emailOld"></param>
        /// <param name="telefono"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult SaveMisDatos(string email, string emailOld, string telefono = "")
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            int UsuarioActive = sso.GetUsuarioActivoID();

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            dbLog.UsuarioID = UsuarioActive;

            try
            {
                bool IsCiudadanoActive = (UsuarioActive > 0);
                if (WebConfig.IsAccesoPublico && IsCiudadanoActive)
                {
                    DTO.Models.Usuario user = appCommon.GetUsuarioByID(UsuarioActive);
                    user.Mail = email;
                    user.Telefono = telefono.Trim();
                    user.UsuarioID = appCommon.SaveUser(user);

                    dbLog.Error = emailOld;
                    dbLog.TipoLog = Enums.TipoLog.CambiarEmailExterno;
                    dbLog.Save();
                }

                return Json(0);
            }
            catch (Exception ex)
            {
                active.SetError(ex, dbLog);
                throw;
            }
        }
        #endregion

        #region Registro Abodago

        /// <summary>
        /// Cambiar email para ciudadnao Logueado.
        /// </summary>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult RegistroAbogado()
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            int UsuarioActive = sso.GetUsuarioActivoID();

            DateTime ahora = DateTime.Now;
            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;

Presentation.Web/Views/Main/Index.cshtml
@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
//ViewBag.Title = "Index";
}

<script type="text/javascript">
    ; (function ($) {
        $(function () {


        });
    })(jQuery);
</script>

<div class="bodyContent">
    <div class="cont">

        <fieldset>
            <legend class="legendTitle">Index</legend>
            @Html.AntiForgeryToken()

        </fieldset>


    </div>
</div>

Presentation.Web/Views/Main/_CambiarEmail.cshtml
@model Application.DTO.Models.Usuario

@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
//var RegionList = ViewBag.RegionList as IList<SIAC.Application.DTO.Models.SP_ListaRegion_Result>;
}

<script type="text/javascript">

    ; (function ($) {
        $(function () {

            $("#newEmail").on('blur', function () { IsEmailValidate($(this)); });

             @if (Model.Mail != "")
            {
                @:ValidarTelefonos();
            }

        });
    })(jQuery);
        
    function saveMisDatos() {

        var newEmail = $.trim($("#newEmail").val());
        var ReingreseEmail = $.trim($("#ReingreseEmail").val());
        var telefono = $.trim($("#Telefono").val()) || "";

        @if (Model.Mail != "")
        {
            <text>
                if (telefono == "" ) {
                    showBlockUIError("Debe Ingresar Télefono");
                    return false;
                }
            </text>
        }

        if (newEmail == "" || ReingreseEmail == "") {
            showBlockUIError("Debe completar los datos de Email");
            return false;
        }

        xJsonObj("@Url.Action("SaveMisDatos", "Main")",
        {
            __RequestVerificationToken: getVToken(),
            email: newEmail,
            emailOld: $.trim("@Model.Mail"),
            telefono: telefono
            },
            $.noop, function ()
            {
                showBlockUI(SelfRedirect);
            })

    }

</script>

<div class="modal-body" style="padding-top: 6px;">

    @if (Model.UsuarioID == 0)
    {
        <div class="alert alert-danger">
            <span>No Es Posible Continuar</span>
        </div>

    }
    else
    {
        <div id="">
            @if (Model.Mail != "")
            {
                <div class="form-group row align-items-center">
                    <label for="" class="col-md-4 col-form-label">@Html.Raw(HttpUtility.HtmlDecode(ViewBag.lblEmail)) actual</label>
                    <div class="col-md-8">
                        <input type="text" class="form-control" maxlength="150" disabled="disabled" id="" name="" value="@Model.Mail" />
                    </div>
                </div>
            }

            <div class="form-group row">
                <label for="newEmail" id="" class="col-md-4 col-form-label">@Html.Raw(HttpUtility.HtmlDecode(ViewBag.lblEmail)) nuevo</label>
                <div class="col-md-8">
                    <input type="text" class="form-control" maxlength="150" id="newEmail" name="newEmail" value="" />
                </div>
            </div>

            <div class="form-group row" id="divReingreseEmail">
                <label for="ReingreseEmail" id="lblReingreseEmail" data-spanverifica="false"
                       class="col-md-4 col-form-label">Reingrese @Html.Raw(HttpUtility.HtmlDecode(ViewBag.lblEmail))</label>
                    <div class="col-md-8">
                        <input type="text" class="verificar form-control IsEmail" maxlength="150"
                               id="ReingreseEmail" name="ReingreseEmail" value="" />
                    </div>
                </div>

            <script>
                $(document).ready(function () {
                    $('#newEmail,#ReingreseEmail').on("cut copy paste", function (e) {
                        e.preventDefault();
                    });

                    $('#ReingreseEmail').on("blur", function (e) {
                        e.preventDefault();
                        var e1 = $.trim($("#newEmail").val());
                        var e2 = $.trim($("#ReingreseEmail").val());

                        if (e1 != "" && e2 != "") {
                            if (e1 != e2) {
                                showBlockUIError("El Correo electrónico no coincide");
                                $("#newEmail,#ReingreseEmail").removeClass("is-valid").addClass("is-invalid");
                                return false;
                            }
                        }
                    });

                });
            </script>

            @if (Model.Mail != "")
            {
                <div class="form-group row align-items-center">
                    <label for="" class="col-md-4 col-form-label">Teléfono <span class="span-obligatorio">*</span></label>
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.Telefono, new { @class = "form-control", @style = "", @placeholder = "Ej. 56987654321", @maxlength = "20" })
                    </div>
                </div>
            }

        </div>
    }



</div>

<div class="modal-footer">


    @if (Model.UsuarioID == 0)
    {
        <button class="btn btn-default" data-dismiss="modal" onclick="SelfRedirect()" type="button">
            <i class="x-icon x-icon-cancel2 icon-in-button"></i> @resources.GlobalResources.BtnAceptar
        </button>
    }
    else
    {
        <button id="btnUpdateEmail" class="btn btn-default" onclick="saveMisDatos()" type="button">                       
                <i class="x-icon x-icon-save2 icon-in-button"></i> @resources.GlobalResources.BtnActualizar
            </button>

            <i class="x-icon-loader hide"></i>
            if (Model.Mail != "")
            {
            <button class="btn btn-default" data-dismiss="modal" type="button">
                <i class="x-icon x-icon-cancel2 icon-in-button"></i> @resources.GlobalResources.BtnCancelar
            </button>
            }

            }


</div>


<div id="modalEmailValidateChange" style="display:none">
    <div title="Validación de Email" id="validateEmailPopupChange">
        <div class="alert alert-danger">
            <strong>POR FAVOR NO CIERRE ESTA VENTANA</strong>
        </div>

        @*@Html.Raw(Html.GetInfoVentana(Enums.TipoVentana.CodigoVerificacion, true))*@

        <div class="form-group">
            <label for="EmailCodeVerificationChange">Código de Verificación</label>
            <input type="text" maxlength="10" class="form-control verificar" id="EmailCodeVerificationChange" name="EmailCodeVerificationChange">
        </div>

    </div>
</div>

Presentation.Web/Views/Main/_MiFirma.cshtml
@model Application.DTO.Models.Usuario

@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
//var RegionList = ViewBag.RegionList as IList<SIAC.Application.DTO.Models.SP_ListaRegion_Result>;
}

<script type="text/javascript">

    ; (function ($) {
        $(function () {

            activateForm("btnSaveSigner", "frmSigner",
               function () {

                   return true;
               },
               function () {

                   CloseDialog();
                   showBlockUI(SelfRedirect());
               });

        });
    })(jQuery);

</script>


<div class="modal-body" style="padding-top: 6px;">

    <form class="" id="frmSigner" action="@Url.Action("SaveMiFirma", "Main")" method="POST">
        @Html.AntiForgeryToken()

        <div class="form-group" style="margin-top: 10px;">
            <input type="text" class="form-control verificar" maxlength="70" id="SignerUserActive" name="SignerUserActive" value="@Model.SignerEncrypted">
        </div>

    </form>

</div>

<div class="modal-footer">

    <button id="btnSaveSigner" class="btn btn-default" onclick="$('#frmSigner').submit()" type="button">
        <i class="x-icon x-icon-save2 icon-in-button"></i> @resources.GlobalResources.BtnGuardar
    </button>
    <i class="x-icon-loader hide"></i>
    <button class="btn btn-default" data-dismiss="modal" type="button">
        <i class="x-icon x-icon-cancel2 icon-in-button"></i> @resources.GlobalResources.BtnCancelar
    </button>

</div>

Presentation.Web/Views/Main/_RegistroAbogado.cshtml
@model Application.DTO.Models.Usuario
@using resources = Infrastructure.Resources;

@{
    bool IsAbogado = (bool)ViewBag.IsAbogado;

    var FormatosPermitidos = ViewBag.FormatosPermitidos as IList<Application.DTO.Models.AsocTipoDocumentoAdjunto>;
}

<script type="text/javascript">

    var SolicitaHabilitar = false;

    ; (function ($) {
        $(function () {
            fixFakePath("archivo");

            $(".xCheckbox").bootstrapSwitch({
                onSwitchChange: function (event, state) {
                    if (state) {
                        $("#divSolicita").show();
                        $("#divTelefono").show();
                        SolicitaHabilitar = true;
                    } else {
                        $("#divSolicita").hide();
                        $("#divTelefono").hide();
                        SolicitaHabilitar = false;
                    }
                }
            });

            activateForm("btnAceptar", "frmRegistroAbogado",
               function () {

                   if (!SolicitaHabilitar) {
                       showBlockUIError("Para el envío de su solicitud, debe indicar que quiere registrarse");
                       return false;
                   }

                   if (!$("#checkDeclarar").is(":checked")) {
                       showBlockUIError("Debe declarar contar con los requisitos solicitados");
                       return false;
                   }

                   if ($("#archivo").val() == "") {
                       showBlockUIError("Debe cargar el certificado de título");
                       return false;
                   }

                   $("#frmFileExpediente").submit();

                   return true;
               },
               function () {

                   showBlockUI(CloseDialog);

               });

            SetUploadForm();
            ValidarTelefonos();

        });
    })(jQuery);

    function SetUploadForm() {

        activateFormUploadFile({
            formID: "frmFileExpediente",
            callback: function () {

                //CloseDialog();              
            }
        })
    }

</script>

<div class="modal-body" style="padding-top: 6px;">

    @if (IsAbogado)
    {
        <fieldset class="x-fieldset">
            @Html.Raw(Html.GetInfoVentanaIpsum("Usted está confirmado como Abogado"))

        </fieldset>
    }
    else
    {

       <fieldset class="x-fieldset">
           @Html.Raw(Html.GetInfoVentana(Domain.Infrastructure.TipoVentana.RegistroAbogado))

           <form class="form-horizontal " id="frmRegistroAbogado" method="post" action="@Url.Action("SolicitudRegistroAbogado", "Main")">
               @Html.AntiForgeryToken()
               @Html.HiddenFor(x => x.UsuarioID)               

               <div class="form-group row align-items-center">
                   <label for="" class="col-md-4 col-form-label">Quiero Registrarme</label>
                   <div class="col-md-6">
                       @Html.Raw(Html.MyCheckbox(false, "IsSolicitaHabilitacion", 0, "", "small", 0, false, false, ""))
                   </div>
               </div>

               <div class="form-group row align-items-center" id="divTelefono" style="display:none;">
                   <label for="" class="col-md-4 col-form-label">Teléfono <span class="span-obligatorio">*</span></label>
                   <div class="col-md-6">
                       @Html.TextBoxFor(x => x.Telefono, new { @class = "form-control verificar", @style = "", @placeholder = "Ej. 56987654321", @maxlength = "20" })
                   </div>
               </div>
              
           </form>
       </fieldset>

    <div id="divSolicita"  style="display:none;">

        <fieldset class="x-fieldset">
            <legend class="celeste bold">Certificado de Título</legend>

            <form class="" id="frmFileExpediente" enctype="multipart/form-data" action="@Url.Action("SubirArchivo", "Uploader")" method="POST">
                @Html.AntiForgeryToken()

                <input type="hidden" id="_TipoDocumentoID" name="TipoDocumentoID" value="@Html.EnumToInt(Domain.Infrastructure.TipoDocumento.CertificadoTituloAbogado)" />


                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input notBlock" id="archivo" name="file">
                        <label class="custom-file-label" for="file"
                               data-browse="@resources.UploadFiles.FileInput_changeText"
                               aria-describedby="inputGroupFileAddon">@resources.UploadFiles.FileInput_inputText</label>
                        </div>
                    </div>

                    <small id="" class="form-text text-muted ac" style="margin-bottom: 10px;">
                        @resources.GlobalResources.ExtensionesPermitidas: @Html.Raw(Html.GetExtensionesPermitidas(FormatosPermitidos, IncluyeTamanio: true))
                    </small>

                </form>
            </fieldset>

            <div class="alert alert-danger ac" role="alert" style="margin-top:5px;">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" id="checkDeclarar" value="1">
                    <label class="form-check-label" for="checkDeclarar"> Declaro contar con todos los requisitos necesarios para registrarme como abogado/a en esta plataforma.</label>
                </div>
            </div>
        </div>
    }



</div>

<div class="modal-footer">

    @if (!IsAbogado)
    {
        <button id="btnAceptar" class="btn btn-default" onclick="$('#frmRegistroAbogado').submit()" type="button">
            <i class="x-icon x-icon-save2 icon-in-button"></i> @resources.GlobalResources.BtnEnviar
        </button>

        <i class="x-icon-loader hide"></i>
    }
    else
    {
        <button class="btn btn-default" data-dismiss="modal" type="button">
            <i class="x-icon x-icon-save2 icon-in-button"></i> @resources.GlobalResources.BtnAceptar
        </button>
    }
    

    <button class="btn btn-default" data-dismiss="modal" type="button">
        <i class="x-icon x-icon-cancel2 icon-in-button"></i> @resources.GlobalResources.BtnCancelar
    </button>

</div>