Presentation.Web/Controllers/ExpedientesController.cs
using Application.DTO.Utils;
using Application.Services;
using Infrastructure.Logging;
using Infrastructure.Utils.Extensions;
using Newtonsoft.Json;
using Presentation.Web.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO = Application.DTO;
using Enums = Domain.Infrastructure;
using WebConfig = Domain.Infrastructure.WebConfigValues;


namespace Presentation.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [SiteContext]
    public class ExpedientesController : GlobalController
    {

        private readonly ICommonAppServices appCommon = new CommonAppServices();
        private readonly IExpedienteAppServices appExpediente = new ExpedienteAppServices();
        private readonly IMailAppServices appMail = new MailAppServices();

        private readonly Commons active = new Commons();

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            bool IsInvitado = sso.IsInvitado();
            bool IsINAPI = sso.IsINAPI();
            bool IsSAG = sso.IsSAG();
            bool IsTDPI = sso.IsTDPI();
            bool IsAbogado = sso.IsAbogado();

            bool acceso = (IsInvitado || IsINAPI || IsSAG || IsTDPI || IsAbogado);
            if (!acceso) return RedirectToRoute("ActionInitialSystem");

            var TipoCausa = appCommon.GetTipoCausa(true);

            IList<DTO.Models.TipoCausa> TipoCausaFilter = active.GetTipoCausaByUserActive(TipoCausa, sso);
            ViewBag.TipoCausaFilter = TipoCausaFilter;

            ViewBag.PuedeIngresarCausa = active.IsPuedeIngresarCausa(sso);

            DTO.FiltrosEscritorio filtros = new DTO.FiltrosEscritorio();
            filtros.TipoCausa = appCommon.GetTipoCausa(true);
            filtros.EstadoCausa = appCommon.GetEstadoCausa(true);

            ViewBag.FiltrosEscritorio = filtros;

            return View();
        }




        /// <summary>
        /// Registro
        /// </summary>
        /// <param name="id"></param>
        /// <param name="id2"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Registro(int id = 0, int id2 = 0)
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            int CausaID = id;
            int TipoCausaID = id2;

            bool IsNew = (CausaID == 0);
            bool IsView = false;

            if (TipoCausaID == 0 && IsNew)
            {
                return Redirect(WebConfig.Url_MenuSistemas);
            }

            var TipoCausa = appCommon.GetTipoCausa(true);
            bool PuedeIngresar = active.IsPuedeIngresarCausa(sso);
            if (!PuedeIngresar) return RedirectToRoute("ActionInitialSystem");

            if (IsNew)
            {
                var TiposPermitidos = active.GetTipoCausaByUserActive(TipoCausa, sso);
                if (!TiposPermitidos.Any(x => x.TipoCausaID == TipoCausaID))
                {
                    return RedirectToRoute("ActionInitialSystem");
                }
            }

            DTO.Models.Causa model = new DTO.Models.Causa();
            model.Anio = DateTime.Now.Year;
            model.TipoCausaID = TipoCausaID;
            model.IsContencioso = true;

            #region Valida Causa y TipoCausa

            if (CausaID != 0)
            {
                try
                {
                    model = appExpediente.GetCausa(CausaID);
                    model.Parte = appExpediente.GetParteByCausa(CausaID);
                    model.DocumentoCausa = appExpediente.GetDocumentoCausa(CausaID, Domain.Infrastructure.TipoDocumento.Causa);
                }
                catch (Exception)
                {
                    Logger.Execute().Error(new System.ArgumentException("No existe Causa", "No existe CausaID " + CausaID));
                    return RedirectToAction("Index");
                }
            }

            var tc = TipoCausa.FirstOrDefault(x => x.TipoCausaID == TipoCausaID);
            if (tc == null)
            {
                Logger.Execute().Error(new System.ArgumentException("No existe TipoCausa", "No existe TipoCausaID " + CausaID));
                return RedirectToAction("Index");
            }
            else
            {
                model.TipoCausa = tc;
            }

            #endregion

            DTO.Models.ConfTipoCausa Config = appCommon.GetConfTipoCausa(TipoCausaID);
            ViewBag.ConfTipoCausa = Config;

            #region DataForm

            DTO.DataForm DataForm = new DTO.DataForm();
            DataForm.UserActive = sso.UserActive;
            DataForm.IsNew = IsNew;
            DataForm.IsView = IsView;
            DataForm.Pais = appCommon.GetPais();
            DataForm.TipoContencioso = appCommon.GetTipoContencioso(true);
            DataForm.TipoParte = appCommon.GetTipoParte(true);
            DataForm.AsocTipoDocumentoAdjunto = appCommon.GetTipoDocumentoAdjuntoByID((int)Enums.TipoDocumento.Causa);

            ViewBag.DataForm = DataForm;

            #endregion


            return View(model);
        }


        #region Parte

        /// <summary>
        /// GetParte
        /// </summary>
        /// <param name="ParteID"></param>
        /// <param name="CausaID"></param>
        /// <param name="TipoParteID"></param>
        /// <param name="TipoCausaID"></param>
        /// <param name="index"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetParte(int ParteID, int CausaID, int TipoParteID, int TipoCausaID, int index)
        {
            try
            {
                DTO.Models.Parte parte = new Application.DTO.Models.Parte();
                parte.CausaID = CausaID;
                parte.TipoParteID = TipoParteID;
                parte.TipoParte = appCommon.GetTipoParte().FirstOrDefault(x => x.TipoParteID == TipoParteID);

                List<int> CausasSinConsignacion = new List<int>();
                CausasSinConsignacion.Add((int)Enums.TipoCausa.VariedadVegetal);
                CausasSinConsignacion.Add((int)Enums.TipoCausa.ProteccionSuplementaria);
                CausasSinConsignacion.Add((int)Enums.TipoCausa.RecursoHechoMarca);
                CausasSinConsignacion.Add((int)Enums.TipoCausa.RecursoHechoPatente);

                List<int> PartesSinConsignacion = new List<int>();
                PartesSinConsignacion.Add((int)Enums.TipoParte.Recurrido);
                PartesSinConsignacion.Add((int)Enums.TipoParte.Apelado);
                PartesSinConsignacion.Add((int)Enums.TipoParte.Solicitante);

                if (ParteID > 0)
                {
                    parte = appExpediente.GetParte(ParteID);
                }

                if (ParteID == (int)Enums.GenericJson.TempData)
                {
                    if (PartesSinConsignacion.Contains(TipoParteID) || CausasSinConsignacion.Contains(TipoCausaID))
                    {
                        string objTemp = active.GetStringValueForm(Request.Form["objTemp"]);
                        DTO.ParteVueSinConsignacion parteVue = JsonConvert.DeserializeObject<DTO.ParteVueSinConsignacion>(objTemp);

                        parte.PaisID = parteVue.PaisID;
                        parte.Rut = parteVue.Rut;
                        parte.Nombre = parteVue.Nombre;
                        parte.RutRepresentante = parteVue.RutRepresentante;
                        parte.NombreRepresentante = parteVue.NombreRepresentante;
                        parte.NombreAbogado = parteVue.NombreAbogado;
                        parte.EmailAbogado = parteVue.EmailAbogado;
                        parte.NombreEstudioJuridico = parteVue.NombreEstudioJuridico;
                        parte.FolioConsignacion = string.Empty;
                        parte.FechaConsignacion = null;
                        parte.RutConsignacion = 0;
                        parte.NombreConsignacion = string.Empty;
                        parte.ParteID = ParteID;
                    }
                    else
                    {
                        string objTemp = active.GetStringValueForm(Request.Form["objTemp"]);
                        DTO.ParteVue parteVue = JsonConvert.DeserializeObject<DTO.ParteVue>(objTemp);

                        parte.PaisID = parteVue.PaisID;
                        parte.Rut = parteVue.Rut;
                        parte.Nombre = parteVue.Nombre;
                        parte.RutRepresentante = parteVue.RutRepresentante;
                        parte.NombreRepresentante = parteVue.NombreRepresentante;
                        parte.NombreAbogado = parteVue.NombreAbogado;
                        parte.EmailAbogado = parteVue.EmailAbogado;
                        parte.NombreEstudioJuridico = parteVue.NombreEstudioJuridico;
                        parte.FolioConsignacion = parteVue.FolioConsignacion;
                        parte.FechaConsignacion = active.GetDateTimeValueOrNull(parteVue.FechaConsignacion);
                        parte.RutConsignacion = parteVue.RutConsignacion;
                        parte.NombreConsignacion = parteVue.NombreConsignacion;
                        parte.ParteID = ParteID;
                    }

                }

                DTO.DataForm DataForm = new DTO.DataForm();
                DataForm.Pais = appCommon.GetPais().Where(x => x.Vigente).ToList();
                ViewBag.DataForm = DataForm;

                DTO.Models.ConfTipoCausa Config = appCommon.GetConfTipoCausa(TipoCausaID);
                ViewBag.ConfTipoCausa = Config;

                ViewBag.Index = index;

                return PartialView("_Parte", parte);
            }
            catch (Exception ex)
            {

Presentation.Web/Views/Expedientes/Index.cshtml
@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
    string PageTitle = "Escritorio TDPI - Gestión de Expedientes";

    Application.DTO.FiltrosEscritorio FiltrosEscritorio = ViewBag.FiltrosEscritorio;
    var DataForm = ViewBag.DataForm as Application.DTO.DataForm;

    bool PuedeIngresar = (bool)ViewBag.PuedeIngresarCausa;// DataForm.PerfilActive.IsTDPI;

    PageTitle = (Domain.Infrastructure.WebConfigValues.IsAccesoPublico) ? "Buscador de Causas" : PageTitle;
    ViewBag.Title = PageTitle;

    var TipoCausa = ViewBag.TipoCausaFilter as IList<Application.DTO.Models.TipoCausa>;

}

<script type="text/javascript">
    var oTableGrid;

    ; (function ($) {
        $(function () {

            $("#btnBuscar").on("click", goGrid);

        });
    })(jQuery);

    function goGrid() {

        $("#divDetalleExpediente").empty();

        var ckeck = $("#radio1").is(":checked");
        if (ckeck) {
            var ticket = $.trim($("#NumeroTicket").val());
            if (ticket == "") {
                showBlockUIError("Debe indicar un Rol");
                return false;
            }
        }

        var ckeck = $("#radio2").is(":checked");
        if (ckeck) {
            var ticket = $.trim($("#NumeroSolicitud").val());
            if (ticket == "") {
                showBlockUIError("Debe indicar N° Solicitud");
                return false;
            }
        }

        var ckeck = $("#radio3").is(":checked");
        if (ckeck) {
            var ticket = $.trim($("#NumeroRegistro").val());
            if (ticket == "") {
                showBlockUIError("Debe indicar N° Registro");
                return false;
            }
        }

        var ckeck = $("#radio4").is(":checked");
        if (ckeck) {

            var anio = $("#Anio").val();

            if (anio == 0) {

                var ticket = $.trim($("#NumeroRegistro").val());
                var Denominacion = $.trim($("#Denominacion").val());
                var Apelante = $.trim($("#Apelante").val());
                var FechaIngreso = $.trim($("#FechaIngreso").val());
                var Apelado = $.trim($("#Apelado").val());
                var EstadoCausaID = $("#EstadoCausaID").val();
                var TipoCausaID = $("#TipoCausaID").val();
                var CheckEscritos = $('#IsSoloEscritos').is(':checked');

                if (ticket == "" && Denominacion == "" && Apelante == "" && FechaIngreso == "" && Apelado == "" && EstadoCausaID == 0 && TipoCausaID == 0 && !CheckEscritos) {
                    showBlockUIError("Debe Ingresar al menos un filtro");
                    return false;
                }
            }
        }       

        var xBtn = $("#btnBuscar");
        blockPageUI();

        xJsonObj("@Url.Action("GetEscritorioTDPI", "Expedientes")", $("#frmFiltrosEscritorio").serialize(),
        function () {
            BtnInAction(xBtn, false, true);
        },
        function () {
            BtnInAction(xBtn, true, true);
            blockPageUIclose();
            loadGrid();
        });

    }

    function loadGrid() {

        var xJSONResultDisplay = new Array();

        $.each(xJSONResult, function (i, item) {

            var Obj = {
                'Contador': (i + 1),
                'ticket': item.ticket,
                'date': item.date,
                'denom': item.denom,
                'tcau': item.tcau,
                'num': item.num,
                'estado': function () {
                    var h = item.ec + '<span class="azul db">' + item.us + '</span>';
                    return h;
                },
                'Acciones': function () {

                    var html = GetIconAction(item.Act);

                    return html;
                },
                'DT_RowId': 'tr_' + i
            }

            xJSONResultDisplay.push(Obj);

        });

        var localGridParams = {
            "bSort": true,
            "aaData": xJSONResultDisplay,
            "fnInitComplete": function (oSettings, json) {

                var findPage = store.get("volver_Expediente_findPage") || 0;
                if (findPage != 0) {
                    if (findPage) {

                        setTimeout(function () {
                            var nPage = parseInt(GetCurrentPage("DeskTDPI"));
                            oTableGrid.fnPageChange(nPage);
                            store.set("volver_Expediente_findPage", false);
                        }, 300);
                    }
                }
            },
            "fnDrawCallback": function (oSettings) {

                callToolTips();

                $("#grilla .x-icon-zoom1, #grilla .x-icon-edit").on("click", function () {
                    SetCurrentPage(oTableGrid.fnPagingInfo().iPage, "DeskTDPI");
                });

            },
            "aoColumns": [{ "sClass": "ac nw", "bSortable": true, "mDataProp": "Contador" },
						  { "sClass": "ac nw", "bSortable": true, "mDataProp": "ticket" },
						  { "sClass": "ac", "bSortable": true, "mDataProp": "date" },
						  { "sClass": "al", "bSortable": true, "mDataProp": "denom" },
						  { "sClass": "al", "bSortable": true, "mDataProp": "tcau" },
						  { "sClass": "ac", "bSortable": true, "mDataProp": "num" },
						  { "sClass": "ac nw", "bSortable": true, "mDataProp": "estado" },
						  { "sClass": "ac nw", "bSortable": false, "mDataProp": "Acciones" }]
        };

        generalGridParams.paging = true;
        generalGridParams.ordering = true;

        var allGridParams = $.extend({}, localGridParams, generalGridParams);
        oTableGrid = $('#grilla').removeClass("hide").dataTable(allGridParams);
    }

    function seleccionarTR(parent, obj) {

        $("#" + parent + " tr").removeClass("selected");

        var tr = $(obj).parents("tr");
        $(tr).addClass("selected");

    }

    function GetEventosExpediente(CausaID, obj) {


        var $divDet = $("#divDetalleExpediente");
        $divDet.html("");

        var before = function () { $divDet.html(divLoaderHtml()); };
        var params = {
            __RequestVerificationToken: getVToken(),
            CausaID: CausaID
        };

        xAjaxHtml("@Url.Action("GetEventosExpediente", "Expedientes")", params, before, function ()
        {
            $divDet.html(DataHTM);

            scrollToElement($divDet);
        });

    }

    @if (PuedeIngresar)
    {<text>

    function CreateExpediente(option) {
       
        var opts = {
            title: "Seleccione Tipo Expediente a Ingresar",
            msg1: $("#btnsAddExpediente").html(),
            url: null,
            params: {},
            id: "myModalConfirmCreate2",
            btn1Hide: true,
            replaceParrafo: true,
            callback: function () {

            }
        }

        xDialogConfirmAction(opts);

    }

    function CreateExpedienteConfirmacion(option) {

        var opts = {
            title: "Solo Ingreso Nuevos Expedientes",
            html: "¿Confirma Crear un Nuevo Expediente?",
            size: "modal-xl",
            url: null,
            params: {},
            id: "myModalConfirmCreate",
            IsHideMessageEnd: true,
            //btn1Hide: true,
            replaceParrafo: true,
            callback: function () {
               
                   
                    end.apply();
             
               
            }
        }

        xAlert_gs(opts);

    }

    </text>}

    function GenerarExpedientePDF(CausaID) {

        let tipoDocumentoID = parseInt("@Html.EnumToInt(Enums.TipoDocumento.ExpedienteElectronicoPDF)");

        xJsonObj("@Url.Action("ActionExpediente", "Expedientes")",
            {
                __RequestVerificationToken: getVToken(),
                action: "@Enums.ActionSystem.GenerarExpedientePDF",
                Identidad: CausaID
            },
            function () {
                blockPageUI();
            }, function () {

                if (xJSONResult.result == ReturnJson.ActionSuccess)
                {
                    setTimeout(function () {
                        blockPageUIclose();
                        getDownloadFile(xJSONResult.d, xJSONResult.i, xJSONResult.h, tipoDocumentoID);
                    }, 1000)

                }
                else
                {
                    showBlockUIError("No fue posible generar el Expediente, favor intente más tarde");
                    return false;
                }

            });
    }

    function GetDeshabilitarExpediente(CausaID) {
        var optBtn = {
            title: "Eliminar Expediente",
            msg1: "¿Confirma la eliminación del Expediente?",
            msg2: "",
            url: "@Url.Action("ActionExpediente", "Expedientes")",
            params: {
            __RequestVerificationToken: getVToken(),
            action: "@Enums.ActionSystem.EliminarExpediente",
                Identidad: CausaID,
            },
        callback: function () {

            showBlockUI(CloseDialog);
            $("#btnBuscar").click();

            //$("#grilla tr.selected a:last i.x-icon-org").click();
        },
        alert: "alert-danger",
        txtBtn1: "Sí"
    }

    xDialogConfirmAction(optBtn);
    }





</script>

<div class="bodyContent">
    <div class="cont">

        <fieldset>
            <legend class="legendTitle">@PageTitle</legend>

            @Html.Raw(Html.GetInfoVentana(Domain.Infrastructure.TipoVentana.EscritorioGestionExpedientes))

            @Html.Partial("_FiltrosEscritorio", FiltrosEscritorio, new ViewDataDictionary {
               { "IsEscritorioTDPI", true },
               { "NamePage", "EscTDPI" }
           })

            <div class="row">
                <div class="col">
                    <button id="btnBuscar" type="button" class="btn btn-default"><i class="x-icon x-icon-zoom1 icon-in-button"></i> @resources.GlobalResources.BtnBuscar</button>
                    <i class="x-icon-loader hide"></i>
                    <button style="" type="button" onclick="LimpiaForm(0)" class="btn btn-default" id="btnLimpiar"><i class="x-icon x-icon-limpiar icon-in-button"></i> @resources.GlobalResources.Limpiar  Filtros</button>
                </div>
            </div>

            <div class="row">
                <div class="col text-right" id="btnsCreateExpediente">
                    @if (PuedeIngresar && !Domain.Infrastructure.WebConfigValues.IsAccesoPublico)
                    {
                        <button type="button" id="" class="btn btn-default"
                                onclick="CreateExpedienteConfirmacion(true)">
                            <i class="x-icon x-icon-mas3 icon-in-button"></i> Solo Ingreso Nuevos Expedientes
                        </button>
                    }

                </div>
            </div>



            <div class="table-responsive-not">
                <table class="table table-striped table-sm table-bordered table-hover x-table allW hide" id="grilla">
                    <thead>
                        <tr>
                            <th class="ac" style="">@resources.GlobalResources.TH_Number</th>
                            <th class="ac" style="">N° Rol TDPI</th>
                            <th class="ac " style="">Fecha</th>
                            <th class="ac" style="text-align: left !important">@resources.Expediente.lblDenominacionHelp</th>
                            <th class="ac" style="">Tipo Causa</th>
                            <th class="ac" style="">N° Solicitud</th>
                            <th class="ac" style="text-align: left !important">Estado<br />Responsable</th>
                            <th class="ac" style="">@resources.GlobalResources.TH_Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>


            <div id="divDetalleExpediente" style="margin-top: 5px;"></div>


        </fieldset>


    </div>
</div>

@if (PuedeIngresar)
{
    <div id="btnsAddExpediente" style="display:none">
        <fieldset class="x-fieldset">
            <legend class="celeste bold">Tipo Expediente</legend>

            @foreach (var item in TipoCausa)
            {
                string url = Url.Action("Registro", "Expedientes", new { @id = 0, @id2 = item.TipoCausaID });

                <button type="button" id="" class="btn btn-default btn-lg btn-block btnVI" onclick="LinkRedirect('@url')">@item.Descripcion</button>
            }

        </fieldset>
    </div>
}

Presentation.Web/Views/Expedientes/_Admisibilidad.cshtml
@model Application.DTO.Models.Expediente

@using Enums = Domain.Infrastructure;
@using resources = Infrastructure.Resources;


@{
    int count = 1;

    int TipoDocumentoEnum = (int)Enums.TipoDocumento.Expediente;
}
<script type="text/javascript">

    ; (function ($) {
        $(function () {

            callToolTipsGrid("fsAdjuntosExp");

            activateForm("btSaveInadmisible", "frmDerivar",
                function () {
                    
                    if (!$("#checkDeclarar").is(":checked")) {
                        showBlockUIError("Debe marcar la casilla de declaración");
                        return false;
                    }
                    return true;
                },
                function () {

                    showBlockUI(CloseDialog);

                    $("#grilla tr.selected i.x-icon-org").click();

                });

        });
    })(jQuery);

</script>

<div class="modal-body">


    <form class="form-horizontal " id="frmDerivar" method="post" action="@Url.Action("ActionExpediente", "Expedientes")">
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.ExpedienteID)
        @Html.HiddenFor(x => x.CausaID)
        @Html.Hidden("Identidad", Model.ExpedienteID)
        @Html.Hidden("action", Enums.ActionSystem.ExpedienteInadmisible)

        <fieldset class="x-fieldset">
            <legend></legend>
            <p class="bold mb0">N° ROL: @Model.Causa.NumeroTicket</p>
        </fieldset>

        <fieldset class="x-fieldset">
            <legend class="celeste bold">Evento</legend>

            <div class="form-group row align-items-center">
                <label for="TipoTramiteID" class="col-md-3 col-form-label" id="">Tipo Trámite </label>
                <div class="col-md-9">
                    <input type="text" class="form-control" disabled="disabled" value="@Model.TipoTramite.Descripcion" />
                </div>
            </div>

            <div class="form-group row align-items-center">
                <label for="" class="col-md-3 col-form-label" id="">Fecha </label>
                <div class="col-md-5">
                    <input type="text" class="form-control" disabled="disabled" value="@Html.DatetimeToString(Model.FechaExpediente, "dd-MM-yyyy HH:mm")" />
                </div>
            </div>

        </fieldset>

        <fieldset class="x-fieldset" id="fsAdjuntosExp">
            <legend class="celeste bold">Documentos adjuntos</legend>

            <div class="table-responsive">

                <table class="@Html.GetBaseTableCSS()" id="">
                    <thead>
                        <tr>
                            <th class="ac" style="">#</th>
                            <th class="ac" style="">Nombre Documento</th>
                            <th class="ac" style="">Descripción</th>
                            <th class="ac" style="">Fecha Carga</th>
                            <th class="ac" style="">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.AsocEscritoDocto.Count > 0)
                        {
                            count = 1;

                            foreach (var item in Model.AsocEscritoDocto)
                            {
                                var doc = item.AsocCausaDocumento.DocumentoCausa;

                                <tr>
                                    <td class="ac">@count</td>
                                    <td class="">@doc.NombreArchivoFisico</td>
                                    <td style="max-width:200px" class="fixWord">@doc.Descripcion</td>
                                    <td class="ac">@Html.DatetimeToString(doc.Fecha, "dd-MM-yyyy HH:mm")</td>
                                    <td class="ac">

                                        <a style="margin-right:2px" href="javascript:void(0)"
                                           onclick='getDownloadFile(@doc.DocumentoCausaID, @Model.CausaID, "@doc.Hash.Trim()", @TipoDocumentoEnum)'
                                           class="x-title-l" title="@resources.GlobalResources.BtnDescargar">
                                            <i class="x-icon @Html.GetCSS(doc.NombreArchivoFisico)" style="cursor: pointer;"></i>
                                        </a>

                                    </td>
                                </tr>
                                count++;
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="5" class="" style="padding:5px 10px;">No hay información para desplegar</td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>


        </fieldset>

        <fieldset class="x-fieldset" id="fsAdjuntosExp">
            @*<legend class="celeste bold">Inadmisible</legend>*@

            <div class="form-group row" id="divComentario">
                <label for="Comentario" class="col-md-3 col-form-label">Comentarios <span class="span-obligatorio">*</span></label>
                <div class="col-md-9">
                    <textarea class="notFilter form-control verificar" name="Comentario" id="Comentario" cols="2" rows="2" maxlength="500"></textarea>
                </div>
            </div>

        </fieldset>

      
        <div class="alert alert-danger ac" role="alert" style="margin-top:5px;">
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="checkDeclarar" value="1">
                <label class="form-check-label" for="checkDeclarar">Declaro que he revisado y decidido eliminar el presente Expediente</label>
            </div>
        </div>

    </form>
</div>

<div class="modal-footer">  

    <button type="button" class="btn btn-default btnAceptar"  onclick="$('#frmDerivar').submit()"  id="btSaveInadmisible"><i class="x-icon x-icon-ok icon-in-button"></i>Si</button><i class="x-icon-loader hide"></i>
    <button class="btn btn-default" data-dismiss="modal" type="button"><i class="x-icon x-icon-cancel2 icon-in-button"></i>No</button>
</div>

Presentation.Web/Views/Expedientes/_HistorialCausa.cshtml
@model Application.DTO.Models.Causa 

@using Enums = Domain.Infrastructure;
@using resources = Infrastructure.Resources;


@{
    int count = 1;    
    var historial = ViewBag.Historial as IList<Application.DTO.Models.LogCausa>;

}
<script type="text/javascript">

    ; (function ($) {
        $(function () {


        });
    })(jQuery);

</script>

<div class="modal-body">


    <fieldset class="x-fieldset">
        <legend></legend>
        <p class="bold mb0">N° ROL: @Model.NumeroTicket</p>
    </fieldset>
        
    <fieldset class="x-fieldset" id="fsCausaHist">
        <legend class="celeste bold">Historial</legend>

        <div class="table-responsive">

            <table class="@Html.GetBaseTableCSS()" id="">
                <thead>
                    <tr>
                        <th class="ac" style="">#</th>
                        <th class="ac" style="">Fecha</th>
                        <th class="ac" style="">Descripción</th>
                        <th class="ac" style="">Usuario</th>
                        <th class="ac" style="">Observaciones</th>
                    </tr>
                </thead>
                <tbody>
                    @if (historial.Count > 0)
                    {
                        count = 1;

                        foreach (var item in historial)
                        {
                            
                            <tr>
                                <td class="ac">@count</td>
                                <td class="nw">@Html.DatetimeToString(item.Fecha, "dd-MM-yyyy HH:mm") </td>
                                <td  class="nw fixWord">@Html.SplitToUpper(item.Descripcion.Trim())</td>
                                <td class="ac">@item.Responsable</td>
                                <td class="ac">@Html.Raw(item.Observaciones.Trim())</td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="5" class="" style="padding:5px 10px;">No hay información para desplegar</td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>


    </fieldset>



</div>

<div class="modal-footer">
    <button class="btn btn-default" data-dismiss="modal" type="button">
        <i class="x-icon x-icon-cancel2 icon-in-button"></i> @resources.GlobalResources.BtnAceptar
    </button>
</div>