Presentation.Web/Controllers/ListadosController.cs
using Application.DTO.Utils;
using Application.Services;
using Infrastructure.Logging;
using Newtonsoft.Json;
using Presentation.Web.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO = Application.DTO;
using Enums = Domain.Infrastructure;
using WebConfig = Domain.Infrastructure.WebConfigValues;

namespace Presentation.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [SiteContext]
    public class ListadosController : GlobalController
    {
        private readonly ICommonAppServices appCommon = new CommonAppServices();
        private readonly IExpedienteAppServices appExpediente = new ExpedienteAppServices();
        private readonly IMailAppServices appMail = new MailAppServices();
        private readonly Commons active = new Commons();
        

        #region Ingreso

        /// <summary>
        /// Index
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            bool acceso = sso.IsTDPI();
            if (!acceso) return Redirect(WebConfig.LogOffAuthenticationSystem);

            DTO.FiltrosEscritorio filtros = new DTO.FiltrosEscritorio();
            ViewBag.FiltrosEscritorio = filtros;

            return View("Ingreso/Index", filtros); //Ingreso\Index
        }


        /// <summary>
        /// GetListadoIngresos
        /// </summary>
        /// <param name="filtros"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetListadoIngresos(DTO.FiltrosEscritorio filtros)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            try
            {
                int UsuarioActive = sso.GetUsuarioActivoID();

                filtros.UsuarioID = UsuarioActive;
                IList<DTO.Models.Causa> lista = appExpediente.GetCausasByFilter(filtros, Enums.TipoGrid.ListadoIngresos);

                ViewBag.Listado = lista;

                return PartialView("Ingreso/_ListadoIngresos");
            }
            catch (Exception ex)
            {
                Logger.Execute().Error(ex);
                throw;
            }
        }


        /// <summary>
        /// 
        /// </summary>
        /// <param name="lista"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GenerarListadoIngresoPDF(string lista)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            DateTime ahora = DateTime.Now;

            DBLogger dbLog = new DBLogger();
            dbLog.Fecha = ahora;
            int UsuarioActive = sso.GetUsuarioActivoID();
            dbLog.UsuarioID = UsuarioActive;

            try
            {
                Enums.ReturnJson retorno = Enums.ReturnJson.SinAccion;

                var listaArray = active.GetStringValueForm(Request.Form["lista"]);
                int[] listaID = JsonConvert.DeserializeObject<int[]>(listaArray);

                DTO.FiltrosEscritorio filtros = new DTO.FiltrosEscritorio();
                filtros.ListaID = listaID;

                IList<DTO.Models.Causa> causas = appExpediente.GetCausasByFilter(filtros, Enums.TipoGrid.PDFListadoIngresos);

                #region PDF
                Enums.TipoDocumento tipoDocumento = Enums.TipoDocumento.Ingreso;

                string FolderSave = string.Format("\\Listados\\{0}\\{1}\\{2}\\{3}", ahora.Year, ahora.Month, tipoDocumento, ahora.ToString("HHmmss"));
                string MergePath = WebConfig.PathBaseRepository + FolderSave;
                if (!Directory.Exists(MergePath)) Directory.CreateDirectory(MergePath);

                DocPdf pdf = new DocPdf();
                pdf.Usuario = sso.UserActive;
                pdf.MapPath = Server.MapPath("~");
                pdf.PathSave = MergePath;
                pdf.Filename = $"IN-{ahora.ToString("dd-MM-yyyy")}.pdf";
                pdf.Titulo = "LISTADO DE INGRESOS";
                pdf.SubTitulo = $"Ingresos de fecha {ahora.ToString("dddd, dd MMMM \\de yyyy")}";
                pdf.CreateDocument("TDPI: Listado de Ingreso");

                pdf.Causas = causas;
                pdf.SetListadoIngreso();
                pdf.Render();

                List<string> emails = new List<string>();
                //emails.Add("test@test.cl");
                //emails.Add("test2@test2.cl");
                #endregion


                #region TheHash

                string PathFinalArchivo = Path.Combine(FolderSave, pdf.Filename);

                DTO.Models.VersionEncript enc = appCommon.GetLastVersionEncript();
                TheHash xEncode = new TheHash(enc.Cadena);
                string EncodeEnd = WebConfig.IsLocalRepository + TipoUploadChar + PathFinalArchivo + TipoUploadChar + 0;
                string SHAFile = xEncode.EncryptData(EncodeEnd);
                #endregion


                #region Save in Store

                DTO.Models.DocumentoSistema doc = new DTO.Models.DocumentoSistema();
                doc.DocumentoSistemaID = 0;
                doc.VersionEncriptID = enc.VersionEncriptID;
                doc.TipoDocumentoID = (int)tipoDocumento;
                doc.Hash = SHAFile;
                doc.NombreArchivoFisico = pdf.Filename;
                doc.Fecha = ahora;
                doc.Descripcion = pdf.SubTitulo;

                doc.DocumentoSistemaID = appExpediente.SaveDocumentoSistema(doc);

                #endregion

                #region Notificacion
                //Notificacion Funcionario
                List<string> destinatarios = appMail.ListadoIngresoDiario(doc.Hash);
                foreach (var item in destinatarios)
                {
                    emails.Add(item);
                }
                #endregion


                int TipoTramiteID = (int)Enums.TipoTramite.Actuacion;
                int OpcionesTramiteID = (int)Enums.OpcionesTramite.Tramite;

                for (int i = 0; i < listaID.Length; i++)
                {
                    int CausaID = listaID[i];

                    active.CreateEventoExpediente(CausaID, TipoTramiteID, OpcionesTramiteID, ahora, UsuarioActive);
                }

                #region LogSistema
                dbLog.TipoLog = Enums.TipoLog.GenerarIngresoPDF;
                dbLog.Save();
                #endregion

                return Json(new
                {
                    result = (int)retorno,
                    emails = string.Join(", ", emails),
                    vs = doc.VersionEncriptID,
                    hash = doc.Hash,
                    documento = doc.DocumentoSistemaID,
                    lista = listaID
                });
            }
            catch (Exception ex)
            {
                Logger.Execute().Error(ex);
                throw;
            }
        }

        #endregion



        #region Tablas


        /// <summary>
        /// Tablas
        /// </summary>
        /// <returns></returns>
        public ActionResult Tablas()
        {
            SsoActionResult sso = new SsoActionResult();
            sso.ExecuteResult(ControllerContext);

            bool acceso = sso.IsTDPI();
            if (!acceso) return Redirect(WebConfig.LogOffAuthenticationSystem);

            DTO.FiltrosEscritorio filtros = new DTO.FiltrosEscritorio();
            filtros.Sala = appCommon.GetSala(true);
            filtros.Usuario = appCommon.GetUsuarios();
            filtros.EstadoTabla = appCommon.GetEstadoTabla();

            return View("Tablas/Index", filtros);
        }


        /// <summary>
        /// GetListadoTablas
        /// </summary>
        /// <param name="filtros"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetListadoTablas(DTO.FiltrosEscritorio filtros)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            try
            {
                filtros.NumeroTicket = active.GetStringValueForm(filtros.NumeroTicket);

                IList<DTO.Models.Tabla> Tablas = appExpediente.GetTabla(filtros);
                IList<DTO.Models.Usuario> Usuarios = appCommon.GetUsuarios();

                foreach (var item in Tablas)
                {
                    var user = Usuarios.FirstOrDefault(x => x.UsuarioID == item.UsuarioRelatorID);
                    item.NombreRelator = user.GetFullName();

                    if (item.IsGenerado() || item.IsPublicado())
                    {
                        item.DocumentoSistemaTabla = appExpediente.GetAsocDocumentoSistema(item.TablaID, Enums.TipoDocumento.Tabla);
                    }
                }

                ViewBag.Listado = Tablas;

                return PartialView("Tablas/_ListadoTablas");
            }
            catch (Exception ex)
            {
                Logger.Execute().Error(ex);
                throw;
            }
        }


        /// <summary>
        /// GetTabla
        /// </summary>
        /// <param name="TablaID"></param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult GetTabla(int TablaID)
        {
            var sso = new SsoActionResult();
            if (!sso.AsyncAuthenticate(ControllerContext)) return Response403();

            try
            {
                DTO.Models.Tabla model = new Application.DTO.Models.Tabla();
                model.TablaID = TablaID;
                model.Fecha = DateTime.Now;
                model.EstadoTablaID = (int)Enums.EstadoTabla.Borrador;

                if (model.TablaID > 0)
                {

Presentation.Web/Views/Listados/Ingreso/Index.cshtml
@model Application.DTO.FiltrosEscritorio

@using resources = Infrastructure.Resources;
@using Enums = Domain.Infrastructure;

@{
    string PageTitle = "Listado de Ingresos";
    ViewBag.Title = PageTitle;

    string OptionInitial = resources.GlobalResources.OptionInicial;

    DateTime FechaDesde = DateTime.Now.AddMonths(-12);
    DateTime FechaHasta = DateTime.Now;

    int AnioOld = DateTime.Now.Year - Domain.Infrastructure.WebConfigValues.AnioInicial;
}

<script type="text/javascript">

    ; (function ($) {
        $(function () {

            $("#btnBuscar").on("click", GetListadoIngresos);
            GetListadoIngresos();

        });
    })(jQuery);

    function GetListadoIngresos() {

        var desde = $.trim($("#FechaDesde").val());
        var hasta = $.trim($("#FechaHasta").val());

        if (desde == "" || hasta == "") {
            showBlockUIError("Debe indicar las fechas Desde/Hasta");
            return false;
        }

        if (!IsFechaValida("FechaDesde")) {
            showBlockUIError("Ingrese una Fecha Desde válida.");
            return false;
        }

        if (!IsFechaValida("FechaHasta")) {
            showBlockUIError("Ingrese una Fecha Hasta válida.");
            return false;
        }

        if (!IsFechaMenorIgual(desde, hasta)) {
            showBlockUIError("La fecha Desde debe ser menor a la Fecha Hasta");
            return false;
        }

        var xBtn = $("#btnBuscar");
        //blockPageUI();

        var $divDet = $("#divListado");
        $divDet.html("");

        var before = function () { $divDet.html(divLoaderHtml()); };
        var params = {
            __RequestVerificationToken: getVToken(),
            FechaDesde: desde,
            FechaHasta: hasta
        };

        xAjaxHtml("@Url.Action("GetListadoIngresos", "Listados")", params, before, function ()
        {
            $divDet.html(DataHTM);
        });

    }

    function GenerarListadoIngresoPDF()
    {
        let selected = $(".checkListado:checked").length;

        if (selected == 0) {
            showBlockUIError("Debe seleccionar al menos un Ingreso");
            return false;
        }

        let lista = [];

        $(".checkListado:checked").each(function () {
            let valor = parseInt($(this).val());
            lista.push(valor);
        });

        xDialogConfirmAction({
            url: "@Url.Action("GenerarListadoIngresoPDF", "Listados")",
            title: "PDF",
            msg1: "¿Confirma generar documento PDF?",
            IsHideMessageEnd: true,
            params: {
                __RequestVerificationToken: getVToken(),
                lista: JSON.stringify(lista)
            },
            callback: function () {
                xAlert({
                    title: "Generación PDF",
                    html: $("#messageEnd").html(),
                    onOpen: function () {

                        var $body = $("#myModalAlert .modal-body");

                        $body.find(".showEmails").html(xJSONResult.emails);

                        var $objDesc = $("#objDescarga", "#myModalAlert .modal-body");
                        $objDesc.attr("data-vs", xJSONResult.vs);
                        $objDesc.attr("data-hash", xJSONResult.hash);
                        $objDesc.attr("data-documento", xJSONResult.documento);
                    },
                    callback: function () {
                        GetListadoIngresos();
                    }
                })
            }

        });
    }

    function MarcarTodo() {

        $(".checkListado").prop("checked", true);
    }

    function DescargarPDF() {

        var $obj = $("#objDescarga", "#myModalAlert .modal-body");

        var vs = $obj.data("vs");
        var hash = $obj.data("hash");
        var documento = $obj.data("documento");
        let TipoDocumentoID = parseInt("@Html.EnumToInt(Enums.TipoDocumento.Ingreso)");

        getDownloadFile(documento, 0, hash, TipoDocumentoID)

    }



</script>

<div id="messageEnd" style="display:none">
    <p>El PDF ha sido generado correctamente y fue notificado por correo a las siguientes casillas de correo: <span class="showEmails bold"></span></p>
    <p>Descargue aqui: <a href="javascript:void(0)" id="objDescarga" class="bold" data-vs="" data-hash="" data-documento="" onclick="DescargarPDF(this)">aqui</a></p>
</div>


<div class="bodyContent">
    <div class="cont">

        <fieldset>
            <legend class="legendTitle">@PageTitle</legend>

            @Html.Raw(Html.GetInfoVentana(Domain.Infrastructure.TipoVentana.ListadosIngreso))

            <fieldset class="x-fieldset">
                <legend class="bold celeste">Filtros</legend>

                <form class="" method="POST" id="frmFiltrosEscritorio" onsubmit="return false" autocomplete="on">
                    @Html.AntiForgeryToken()

                    <div class="row ">
                        <div class="col-md-6">
                            <div class="form-group row">
                                <label for="FechaDesde" class="col-sm-4 col-form-label">Fecha Desde</label>
                                <div class="col-sm-8 col-lg-5">
                                    <div class="input-group">
                                        @Html.TextBoxFor(x => x.FechaDesde, new
                                       {
                                           @Value = FechaDesde.ToString("dd-MM-yyyy"),
                                           @class = "ac IsCalendar form-control",
                                           @style = "",
                                           @placeholder = "",
                                           @maxlength = "10",
                                           @data_year_range = string.Format("-{0}:+1", AnioOld),
                                           @data_max_date = "+12m"
                                       })
                                        <div class="input-group-append">
                                            <span class="input-group-text" id=""><i class="x-icon x-icon-calendar" data-dateinput="FechaDesde"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="col-md-6">
                            <div class="form-group row">
                                <label for="FechaHasta" class="col-sm-4 col-form-label">Fecha Hasta</label>
                                <div class="col-sm-8 col-lg-5">
                                    <div class="input-group">
                                        @Html.TextBoxFor(x => x.FechaHasta, new
                                       {
                                           @Value = FechaHasta.ToString("dd-MM-yyyy"),
                                           @class = "ac IsCalendar form-control",
                                           @style = "",
                                           @placeholder = "",
                                           @maxlength = "10",
                                           @data_year_range = string.Format("-{0}:+1", AnioOld),
                                           @data_max_date = "+30d"
                                       })
                                        <div class="input-group-append">
                                            <span class="input-group-text" id=""><i class="x-icon x-icon-calendar" data-dateinput="FechaHasta"></i></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>

            </fieldset>

        </fieldset>

        <div class="row">
            <div class="col">
                <button id="btnBuscar" type="button" class="btn btn-default"><i class="x-icon x-icon-zoom1 icon-in-button"></i> @resources.GlobalResources.BtnBuscar</button>
                <i class="x-icon-loader hide"></i>
            </div>
        </div>
        <div class="row">
            <div class="col text-right" id="">
                <button type="button" id="" class="btn btn-default" onclick="GenerarListadoIngresoPDF()">
                    <i class="x-icon x-icon-pdf icon-in-button"></i> Generar PDF</button>

                <button type="button" id="" class="btn btn-default" onclick="MarcarTodo()">
                    <i class="x-icon x-icon-check2 icon-in-button"></i> Marcar Todos</button>
            </div>
        </div>


        <div id="divListado"></div>

    </div>
</div>

Presentation.Web/Views/Listados/Ingreso/_ListadoIngresos.cshtml
@using Enums = Domain.Infrastructure;
@using resources = Infrastructure.Resources;

@{

    int count = 1;

    var Listado = ViewBag.Listado as IList<Application.DTO.Models.Causa>;

}

<script type="text/javascript">

    var oTableGrid;

    ; (function ($) {
        $(function () {

            var localGridParams = {

            }

            generalGridParams.paging = false;
            generalGridParams.ordering = false;

            var allGridParams = $.extend({}, localGridParams, generalGridParams);
            oTableGrid = $('#grilla').removeClass("hide").dataTable(allGridParams);
        });
    })(jQuery);



</script>


<div class="table-responsive-not">
    <table class="table table-striped table-sm table-bordered table-hover x-table allW" id="grilla">
        <thead>
            <tr>
                <th class="ac" style="">@resources.GlobalResources.TH_Number</th>
                <th class="ac nw" style="text-align: center !important">N° Rol TDPI</th>
                <th class="ac " style="text-align: center !important">Fecha</th>
                <th class="ac" style="text-align: left !important">@resources.Expediente.lblDenominacion</th>
                <th class="ac" style="text-align: center !important">Días Transcurridos</th>
                <th class="ac nw" style="text-align: center !important">N° Solicitud</th>
                <th class="ac nw" style="text-align: center !important">Estado</th>
                <th class="ac" style="">@resources.GlobalResources.Seleccionar</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Listado)
            {
                <tr>
                    <td class="ac">@count</td>
                    <td class="ac nw">@item.NumeroTicket</td>
                    <td class="ac nw">@Html.DatetimeToString(item.FechaIngreso, "dd-MM-yyyy HH:mm")</td>
                    <td>@item.Denominacion</td>
                    <td class="ac">@item.GetDiasTranscurridos()</td>
                    <td class="ac nw" >@item.Numero</td>
                    <td class="nw">@item.EstadoCausa.Descripcion</td>
                    <td class="ac">
                        <input type="checkbox" class="checkListado" value="@item.CausaID" />
                    </td>
                </tr>
                count++;
            }
        </tbody>
    </table>
</div>